"""initial schema

Revision ID: a2e3d26ff009
Revises: 
Create Date: 2026-04-30 16:31:58.642658

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a2e3d26ff009'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('permissions',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('code', sa.String(length=100), nullable=False),
    sa.Column('description', sa.String(length=255), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('code')
    )
    op.create_table('roles',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('name', sa.String(length=50), nullable=False),
    sa.Column('description', sa.String(length=255), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('stores',
    sa.Column('store_id', sa.String(length=10), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('store_type', sa.Enum('flagship', 'regular', 'outlet', 'express', name='storetype'), nullable=False),
    sa.Column('status', sa.Enum('active', 'inactive', 'temporarily_closed', name='storestatus'), nullable=False),
    sa.Column('latitude', sa.Float(), nullable=False),
    sa.Column('longitude', sa.Float(), nullable=False),
    sa.Column('address_street', sa.String(length=255), nullable=False),
    sa.Column('address_city', sa.String(length=100), nullable=False),
    sa.Column('address_state', sa.String(length=2), nullable=False),
    sa.Column('address_postal_code', sa.String(length=5), nullable=False),
    sa.Column('address_country', sa.String(length=3), nullable=False),
    sa.Column('phone', sa.String(length=12), nullable=False),
    sa.Column('hours_mon', sa.String(length=20), nullable=False),
    sa.Column('hours_tue', sa.String(length=20), nullable=False),
    sa.Column('hours_wed', sa.String(length=20), nullable=False),
    sa.Column('hours_thu', sa.String(length=20), nullable=False),
    sa.Column('hours_fri', sa.String(length=20), nullable=False),
    sa.Column('hours_sat', sa.String(length=20), nullable=False),
    sa.Column('hours_sun', sa.String(length=20), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('store_id')
    )
    op.create_index('idx_stores_active_status', 'stores', ['status'], unique=False)
    op.create_index('idx_stores_lat_lon', 'stores', ['latitude', 'longitude'], unique=False)
    op.create_index(op.f('ix_stores_address_postal_code'), 'stores', ['address_postal_code'], unique=False)
    op.create_index(op.f('ix_stores_store_id'), 'stores', ['store_id'], unique=False)
    op.create_index(op.f('ix_stores_store_type'), 'stores', ['store_type'], unique=False)
    op.create_table('role_permissions',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('role_id', sa.Integer(), nullable=False),
    sa.Column('permission_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['permission_id'], ['permissions.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['role_id'], ['roles.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('role_id', 'permission_id', name='uq_role_permission')
    )
    op.create_table('store_services',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('store_id', sa.String(length=10), nullable=False),
    sa.Column('service_name', sa.String(length=50), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['store_id'], ['stores.store_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_store_services_service_name'), 'store_services', ['service_name'], unique=False)
    op.create_index(op.f('ix_store_services_store_id'), 'store_services', ['store_id'], unique=False)
    op.create_table('users',
    sa.Column('user_id', sa.String(length=20), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('password_hash', sa.String(length=255), nullable=False),
    sa.Column('role_id', sa.Integer(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('must_change_password', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['role_id'], ['roles.id'], ),
    sa.PrimaryKeyConstraint('user_id')
    )
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    op.create_table('refresh_tokens',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.String(length=20), nullable=False),
    sa.Column('token_hash', sa.String(length=255), nullable=False),
    sa.Column('expires_at', sa.DateTime(), nullable=False),
    sa.Column('is_revoked', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.user_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_refresh_tokens_token_hash'), 'refresh_tokens', ['token_hash'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_refresh_tokens_token_hash'), table_name='refresh_tokens')
    op.drop_table('refresh_tokens')
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.drop_table('users')
    op.drop_index(op.f('ix_store_services_store_id'), table_name='store_services')
    op.drop_index(op.f('ix_store_services_service_name'), table_name='store_services')
    op.drop_table('store_services')
    op.drop_table('role_permissions')
    op.drop_index(op.f('ix_stores_store_type'), table_name='stores')
    op.drop_index(op.f('ix_stores_store_id'), table_name='stores')
    op.drop_index(op.f('ix_stores_address_postal_code'), table_name='stores')
    op.drop_index('idx_stores_lat_lon', table_name='stores')
    op.drop_index('idx_stores_active_status', table_name='stores')
    op.drop_table('stores')
    op.drop_table('roles')
    op.drop_table('permissions')
    # ### end Alembic commands ###
